"""empty message

Revision ID: 0ebb3feb5247
Revises: 9d01bfe1eedb
Create Date: 2024-05-15 20:40:50.452976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ebb3feb5247'
down_revision = '9d01bfe1eedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codtipo', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipoquestao', ['codtipo'], ['codTipo'])
        batch_op.drop_column('tipo')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acessoUsuario', sa.String(length=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('acessoUsuario')

    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('codtipo')

    # ### end Alembic commands ###
