"""empty message

Revision ID: 167e1c566231
Revises: be792d6d3f2e
Create Date: 2023-05-31 18:30:59.256521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167e1c566231'
down_revision = 'be792d6d3f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'alunos', ['aluno_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('aluno_id')

    # ### end Alembic commands ###
