"""empty message

Revision ID: 27a2df3c6c1c
Revises: 96b1ae1f8f0a
Create Date: 2023-05-31 16:56:05.556132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27a2df3c6c1c'
down_revision = '96b1ae1f8f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('instituicao_ensino',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('instituicao_ensino',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)

    # ### end Alembic commands ###
