"""empty message

Revision ID: 4a3340a0bbc4
Revises: 9632df37f1d7
Create Date: 2024-06-06 19:57:47.058061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3340a0bbc4'
down_revision = '9632df37f1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.alter_column('tempo_prova',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.alter_column('tempo_prova',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
