"""empty message

Revision ID: 5659f704cf2e
Revises: df1c5c93e179
Create Date: 2023-06-05 19:06:13.527798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5659f704cf2e'
down_revision = 'df1c5c93e179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repostaCorreta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_column('repostaCorreta')

    # ### end Alembic commands ###
