"""empty message

Revision ID: 7607842a6f13
Revises: 167e1c566231
Create Date: 2023-06-05 18:53:00.007376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7607842a6f13'
down_revision = '167e1c566231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.drop_constraint('questoes_ibfk_1', type_='foreignkey')
        batch_op.drop_column('prova_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prova_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('questoes_ibfk_1', 'provas', ['prova_id'], ['id'])

    # ### end Alembic commands ###
