"""empty message

Revision ID: 9632df37f1d7
Revises: f20b8c88cf14
Create Date: 2024-06-03 23:00:07.220711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9632df37f1d7'
down_revision = 'f20b8c88cf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.alter_column('descricaoQuestao',
               existing_type=mysql.VARCHAR(length=600),
               type_=sa.String(length=6000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.alter_column('descricaoQuestao',
               existing_type=sa.String(length=6000),
               type_=mysql.VARCHAR(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###
