"""empty message

Revision ID: 96b1ae1f8f0a
Revises: 
Create Date: 2023-05-29 12:20:19.370972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b1ae1f8f0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('instituicao_ensino', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('senha', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternativa', sa.String(length=1), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    op.drop_table('questoes')
    op.drop_table('provas')
    op.drop_table('alunos')
    # ### end Alembic commands ###
