"""empty message

Revision ID: be792d6d3f2e
Revises: 27a2df3c6c1c
Create Date: 2023-05-31 18:24:16.808253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be792d6d3f2e'
down_revision = '27a2df3c6c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
