"""empty message

Revision ID: d1146c27431b
Revises: 0ebb3feb5247
Create Date: 2024-05-15 21:20:38.548412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1146c27431b'
down_revision = '0ebb3feb5247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('acessoUsuario',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('acessoUsuario',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)

    # ### end Alembic commands ###
