"""empty message

Revision ID: df1c5c93e179
Revises: 7607842a6f13
Create Date: 2023-06-05 18:53:46.476312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df1c5c93e179'
down_revision = '7607842a6f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_column('alternativa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternativa', mysql.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
