"""empty message

Revision ID: e55961ca1ac2
Revises: 5659f704cf2e
Create Date: 2023-06-08 15:45:53.096744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55961ca1ac2'
down_revision = '5659f704cf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repostaCorreta', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.drop_column('repostaCorreta')

    # ### end Alembic commands ###
